#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

  __ _  ___  ___       _ __ ___ (_)_ __ (_)     | (_)_ __  _   ___  __
 / _` |/ _ \/ __|_____| '_ ` _ \| | '_ \| |_____| | | '_ \| | | \ \/ /
| (_| | (_) \__ \_____| | | | | | | | | | |_____| | | | | | |_| |>  <
 \__,_|\___/|___/     |_| |_| |_|_|_| |_|_|     |_|_|_| |_|\__,_/_/\_\



Welcome to aos-mini-linux
Type CTRL-A x to exit QEMU

!
exec /bin/sh



